version: 0.2

phases:
  install: 
    commands:
      - sudo apt-get update
      - sudo apt-get -f install
      - sudo apt-get install python2
      - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build:$ENVIRONMENT
  post_build:
    commands:
      - aws s3 sync ./build $S3_BUCKET 