version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
      php: 7.4
    commands:
      - echo "Installing dependencies..."
      - npm install
      - composer install
  build:
    commands:
      - echo "Building static website..."
      - npm run build
      - echo "
