version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building static website...
      - npm run build
  post_build:
    commands:
      - echo Deploying static website to S3...
      - aws s3 sync --delete ./build s3://george-cicd-project-2
artifacts:
  files:
    - '**/*'
